### ISSUE TITLE
Add ZMQ code in order to connect with judge-backend.

### ISSUE THREAD

**Issue by pin3da** [in-silico/judge-bot#13]

**Comment by h3ct0rjs** [comment]
I was thinking which would be the best way to achieve this,I think that the idea is to create a *_zeromq server *_ (perhaps _zeromq package  should be installed in the docker image_) so this zeromq server should use nodejs as it's mentioned [here ](http://blog.rastating.com/using-zeromq-with-node-js/) or I'm not pretty sure if it's the way, start the container with the [port mapping](https://docs.docker.com/v1.4/userguide/usingdocker/#a-network-port-shortcut) to expose zeromq on the host or server and finally  judge-backend send the data to this. 

What do you think @jhonber @pin3da ?

**Comment by pin3da** [comment]
The zeromq peer (or server), will be outside of the docker container. As far as I know, the data will be shared between the host and the docker image using a 'data volume', in that case we don't need any port exposure.

**Comment by h3ct0rjs** [comment]
Crystal clear it's a pretty cool feature of docker.I Need to do a work around
