### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by jhonber** [in-silico/judge-bot#14]
Is necessary the modularization of judge.sh into several files with specific tasks

**Comment by pin3da** [comment]
Did you mean 'judge.sh' ?

We also need to add a different checker

**Comment by jhonber** [comment]
:+1: 

checker ?

**Comment by pin3da** [comment]
Yes, it would be nice if we use a checker instead of 'diff', in that way is easier to create special-judge problems

**Comment by jhonber** [comment]
Oh yeah, I will open a new issue for that.
