### ISSUE TITLE
Create Dockerfile for image to run submissions

### ISSUE THREAD

**Issue by jhonber** [in-silico/judge-bot#9]
Initial requirements:
Image based on Debian testing with support for the following languages:
C, C++, Python and Java.

**Comment by jhonber** [comment]
If you want to contribute to this issue please read first [Dockerfile best practices](https://docs.docker.com/engine/articles/dockerfile_best-practices/)

**Comment by pin3da** [comment]
I made [this](https://github.com/pin3da/docker-zeromq-node) a while ago. It might help.

**Comment by jhonber** [comment]
https://github.com/in-silico/judge-bot/commit/8ab2541e718be346eecd8ea6a3f487c31e29308e
